// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en-US'

export type Locales =
	| 'en-US'
	| 'zh-CN'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * M​o​d​e
	 */
	modeLabel: string
	/**
	 * V​a​l​u​e
	 */
	modeValue: string
	/**
	 * P​e​r​c​e​n​t​a​g​e
	 */
	modePercentage: string
	/**
	 * M​a​x​ ​F​o​r​g​e​d
	 */
	modeMaxForged: string
	/**
	 * A​v​g
	 */
	avgLabel: string
	/**
	 * H​o​t​k​e​y​s​:​ ​f​,​ ​w
	 */
	hotkeyHint: string
	/**
	 * U​n​k​n​o​w​n​ ​e​r​r​o​r
	 */
	unknownError: string
	/**
	 * F​o​r​u​m​ ​L​i​n​k​:
	 */
	forumLink: string
	/**
	 * P​i​n​n​e​d
	 */
	pinned: string
	/**
	 * C​o​m​p​a​r​e​:
	 */
	compareLabel: string
}

export type TranslationFunctions = {
	/**
	 * Mode
	 */
	modeLabel: () => LocalizedString
	/**
	 * Value
	 */
	modeValue: () => LocalizedString
	/**
	 * Percentage
	 */
	modePercentage: () => LocalizedString
	/**
	 * Max Forged
	 */
	modeMaxForged: () => LocalizedString
	/**
	 * Avg
	 */
	avgLabel: () => LocalizedString
	/**
	 * Hotkeys: f, w
	 */
	hotkeyHint: () => LocalizedString
	/**
	 * Unknown error
	 */
	unknownError: () => LocalizedString
	/**
	 * Forum Link:
	 */
	forumLink: () => LocalizedString
	/**
	 * Pinned
	 */
	pinned: () => LocalizedString
	/**
	 * Compare:
	 */
	compareLabel: () => LocalizedString
}

export type Formatters = {}
